#!/usr/bin/env sh

VERSION_ARG=""
if [ "$DOCKER_TAG" != "master" ] && [ "$DOCKER_TAG" != "latest" ]; then
  VERSION_ARG="==$DOCKER_TAG"
fi

docker build --build-arg VERSION_ARG="$VERSION_ARG" -t ${IMAGE_NAME} .
